import { Router } from 'express';
import PDFDocument from 'pdfkit';
import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma.js';
import { HttpError } from '../lib/http.js';
import { requireAuth } from '../middleware/auth.js';
import { env } from '../config/env.js';
import { getLastUnits } from '../services/invoice.service.js';

export const pdfRouter = Router();
pdfRouter.use(requireAuth);

function tenantWhere(userType: string, userId: number): Prisma.TenantWhereInput {
  return userType === 'SA' ? {} : { parentId: userId };
}

/* ------------------------------------------------------------------ */
/*  GET /api/invoices/:id/pdf                                          */
/* ------------------------------------------------------------------ */
pdfRouter.get('/:id/pdf', async (req, res, next) => {
  try {
    const invoice = await prisma.invoice.findFirst({
      where: {
        id: Number(req.params.id),
        tenant: { ...tenantWhere(req.user!.userType, req.user!.id) },
      },
      include: {
        tenant: { select: { id: true, name: true, roomNo: true, phone: true, rentAmount: true } },
      },
    });

    if (!invoice) throw new HttpError(404, 'Invoice not found');

    const prevUnits = await getLastUnits(invoice.tenantId, invoice.month);
    const currentUnits = Number(invoice.electricityUnits);
    const consumedUnits = Math.max(currentUnits - prevUnits, 0);
    const dueAmount = Number(invoice.totalAmount) - Number(invoice.receivedAmount);

    // Filename: Invoice_{tenant_slug}_{month}.pdf
    const tenantSlug = invoice.tenant.name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_]/g, '');
    const filename = `Invoice_${tenantSlug}_${invoice.month}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    doc.pipe(res);

    // Title
    doc.fontSize(20).font('Helvetica-Bold').text('Room Rent Invoice', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).font('Helvetica').text(`Invoice #${invoice.id}`, { align: 'center' });
    doc.moveDown(1.5);

    // Tenant info
    doc.fontSize(11).font('Helvetica-Bold').text('Tenant Details');
    doc.moveDown(0.3);
    doc.fontSize(10).font('Helvetica');
    doc.text(`Name: ${invoice.tenant.name}`);
    doc.text(`Room: ${invoice.tenant.roomNo}`);
    doc.text(`Phone: ${invoice.tenant.phone}`);
    doc.text(`Month: ${invoice.month}`);
    doc.moveDown(1);

    // Line items table
    doc.fontSize(11).font('Helvetica-Bold').text('Invoice Breakdown');
    doc.moveDown(0.5);

    const tableTop = doc.y;
    const col1 = 50;
    const col2 = 350;

    doc.fontSize(10).font('Helvetica');

    function row(label: string, value: string, y: number) {
      doc.text(label, col1, y);
      doc.text(value, col2, y, { width: 150, align: 'right' });
    }

    let y = tableTop;
    row('Rent', `₹ ${Number(invoice.totalAmount) - Number(invoice.electricityCharge) - Number(invoice.waterCharge)}`, y);
    y += 20;

    // Electricity with breakdown
    row('Electricity', `${currentUnits} - ${prevUnits} = ${consumedUnits} units × ₹${env.ELECTRIC_RATE}`, y);
    y += 20;
    row('Electricity Charge', `₹ ${Number(invoice.electricityCharge)}`, y);
    y += 20;

    row('Water Charge', `₹ ${Number(invoice.waterCharge)}`, y);
    y += 25;

    // Totals
    doc.font('Helvetica-Bold');
    row('Total Amount', `₹ ${Number(invoice.totalAmount)}`, y);
    y += 20;
    doc.font('Helvetica');
    row('Received Amount', `₹ ${Number(invoice.receivedAmount)}`, y);
    y += 20;
    doc.font('Helvetica-Bold');
    row('Due Amount', `₹ ${dueAmount}`, y);
    y += 30;

    // Status
    doc.font('Helvetica').fontSize(9).text(
      dueAmount <= 0 ? 'Status: PAID' : 'Status: DUE',
      col1,
      y,
    );

    // Footer
    doc.moveDown(3);
    doc.fontSize(8).text('Generated by Room Rent Manager', { align: 'center' });

    doc.end();
  } catch (error) {
    return next(error);
  }
});
